feat: Auth service
StraightToJaneStreet/RSLang pull request #16
Opened 2022-08-21 17:01 UTC by laiker

Реализована регистрация и авторизация пользователя. Авторизация запоминается и хранится в localstorage

2022-08-21 17:15 UTC, AlexeiKozovski commented
ok

2022-08-21 17:18 UTC, AlexeiKozovski approved these changes
ok

2022-08-21 17:37 UTC, StraightToJaneStreet requested changes
Накидал замечаний

2022-08-21 17:37 UTC, StraightToJaneStreet commented on package.json
> +  "devDependencies": {
Второй eslint в зависимостях.

2022-08-21 17:37 UTC, StraightToJaneStreet commented on src/model/feature/user.ts
> +      state.refreshToken = payload?.refreshToken as string;
Ошибка в типизации. Если name не передан то будет undefined as string. Сделай так чтобы поля в нагрузке были обязательны

2022-08-21 17:37 UTC, StraightToJaneStreet commented on src/services/AuthService.ts
> +      if ('error' in data) {
Используй Type Guard из обсуждения в #technical

2022-08-21 17:37 UTC, StraightToJaneStreet commented on src/services/RegisterService.ts
> +        const message = 'data' in errResponse.error ? errResponse.error.data : 'message' in errResponse.error ? errResponse.error.message : 'Неизвестная ошибка';
Тоже Type Guard

2022-08-21 17:37 UTC, StraightToJaneStreet commented on src/services/RegisterService.ts
> +        store.dispatch(setRegisterMessage(message as string));
Опять приведение непонятно чего к stirng

2022-08-21 17:37 UTC, StraightToJaneStreet commented on src/services/interfaces/ITabPanelProps.ts
> +
Не выкидывай типы для пропсов в отдельный файл, определяй рядом с компонентом.

2022-08-22 13:58 UTC, laiker commented
@StraightToJaneStreet замечания поправил, можно смотреть

2022-08-22 17:06 UTC, StraightToJaneStreet approved these changes

2022-08-22 17:06 UTC, merged